<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="laser_offset_x" value="0.0075"/>
    <xacro:property name="laser_radius" value="0.035"/>
    <xacro:property name="laser_thickness" value="0.02"/>
    <xacro:property name="laser_mass" value="0.1"/>
    <xacro:property name="laser_base_length" value="0.09"/>
    <xacro:property name="laser_base_width" value="0.07"/>
    <xacro:property name="laser_base_height" value="0.034"/><!-- 5.4cm w.r.t chessis top, 3.4cm base height -->
    <xacro:property name="laser_base_mass" value="0.5"/>

    <!-- LASER BASE LINK -->
    <joint name="laser_base_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser_base"/>
        <origin xyz="${laser_base_length/2 - laser_radius - laser_offset_x} 0 ${chassis_height/2 + laser_base_height/2}" rpy="0 0 0"/>
    </joint>

    <link name="laser_base">
        <visual>
            <geometry>
                <box size="${laser_base_length} ${laser_base_width} ${laser_base_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${laser_base_length} ${laser_base_width} ${laser_base_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${laser_base_mass}" x="${laser_base_length}" y="${laser_base_width}" z="${laser_base_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <gazebo reference="laser_base">
        <material>Gazebo/White</material>
    </gazebo>

    <joint name="laser_joint" type="fixed">
        <parent link="chassis" />
        <child link="laser_frame" />
        <origin xyz="${-laser_offset_x} 0 ${chassis_height/2 + laser_base_height + laser_thickness/2}" rpy="0 0 0" />
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_thickness}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${laser_mass}" radius="${laser_radius}" length="${laser_thickness}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="laser_frame">
        <material>Gazebo/Red</material>

        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan> 
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>
</robot>